import type { EnvironmentConfig } from '../types'

export const presets: Record<string, EnvironmentConfig> = {
  'dark-studio': {
    name: 'Dark Studio',
    bgColor: '#15151a',
    backgroundColor: '#15151a',
    envSource: 'static-lightformers',
    dreiPreset: 'city',
    envBackground: false,
    envBlur: 0,
    ambientIntensity: 0,
    hemisphereLight: true,
    hemisphereIntensity: 0.5,
    spotLight: false,
    spotIntensity: 2,
    accentRing: true,
    decorativeRings: true,
    gradientSphere: false,
    gradientColorBase: '#444444',
    gradientColorA: '#0000ff',
    gradientColorB: '#000000',
    shadowBlur: 0.5,
    shadowOpacity: 1,
  },
  'animated-studio': {
    name: 'Animated Studio',
    bgColor: '#000000',
    backgroundColor: '#000000',
    envSource: 'animated-lightformers',
    dreiPreset: 'city',
    envBackground: true,
    envBlur: 1,
    ambientIntensity: 0.5,
    hemisphereLight: false,
    hemisphereIntensity: 0.5,
    spotLight: true,
    spotIntensity: 2,
    accentRing: true,
    decorativeRings: false,
    gradientSphere: true,
    gradientColorBase: '#444444',
    gradientColorA: '#0000ff',
    gradientColorB: '#000000',
    shadowBlur: 0.5,
    shadowOpacity: 1,
  },
  'sunset-studio': {
    name: 'Sunset',
    bgColor: '#c27d4e',
    backgroundColor: '#1a1410',
    envSource: 'preset',
    dreiPreset: 'sunset',
    envBackground: true,
    envBlur: 0.65,
    ambientIntensity: 0,
    hemisphereLight: false,
    hemisphereIntensity: 0.5,
    spotLight: false,
    spotIntensity: 2,
    accentRing: false,
    decorativeRings: false,
    gradientSphere: false,
    gradientColorBase: '#444444',
    gradientColorA: '#0000ff',
    gradientColorB: '#000000',
    shadowBlur: 1.5,
    shadowOpacity: 0.7,
  },
  'bright-studio': {
    name: 'Bright Studio',
    bgColor: '#f5f5f5',
    backgroundColor: '#f5f5f5',
    envSource: 'preset',
    dreiPreset: 'city',
    envBackground: false,
    envBlur: 0,
    ambientIntensity: Math.PI,
    hemisphereLight: false,
    hemisphereIntensity: 0.5,
    spotLight: false,
    spotIntensity: 2,
    accentRing: false,
    decorativeRings: false,
    gradientSphere: false,
    gradientColorBase: '#444444',
    gradientColorA: '#0000ff',
    gradientColorB: '#000000',
    shadowBlur: 1.5,
    shadowOpacity: 0.9,
  },
}

export const presetKeys = Object.keys(presets)

export const DEFAULT_EFFECTS = {
  bloomEnabled: true,
  bloomIntensity: 1.5,
  bloomThreshold: 0.2,
  aoEnabled: false,
  aoRadius: 0.5,
  aoIntensity: 1,
  vignetteEnabled: false,
  vignetteOffset: 0.3,
  vignetteDarkness: 0.7,
  lutEnabled: true,
}
