import { useState, useCallback, useMemo, useRef, Suspense, type ComponentPropsWithoutRef } from 'react'
import * as THREE from 'three'
import { useGLTF, useEnvironment, Text } from '@react-three/drei'
import { Select } from '@react-three/postprocessing'
import { Price } from './Price'

import kitchenModel from './kitchen-transformed.glb?url'
import interFont from './Inter-Regular.woff?url'

type ItemName = 'BRÖNDEN' | 'VOXLÖV' | 'FANBYN' | 'LIVSVERK' | 'SKAFTET'
const prices: Record<ItemName, number> & { default: number } = {
  KNOXHULT: 5999,
  BRÖNDEN: 433,
  SKAFTET: 77,
  FANBYN: 255,
  VOXLÖV: 1699,
  LIVSVERK: 44,
  default: 5999,
} as Record<ItemName, number> & { default: number }

function debounce<F extends (...args: any[]) => void>(fn: F, wait: number): F {
  let t: ReturnType<typeof setTimeout> | null = null
  return ((...args: Parameters<F>) => {
    if (t) clearTimeout(t)
    t = setTimeout(() => fn(...args), wait)
  }) as F
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 kitchen.glb --transform
*/
export function Kitchen(props: ComponentPropsWithoutRef<'group'>) {
  const { nodes, materials } = useGLTF(kitchenModel) as unknown as {
    nodes: Record<string, THREE.Mesh>
    materials: Record<string, THREE.Material>
  }
  const env = useEnvironment({ preset: 'city' })
  const [hovered, hover] = useState<ItemName | null>(null)
  const lastHovered = useRef(hovered)
  lastHovered.current = hovered
  const debouncedHover = useMemo(() => debounce((v: ItemName | null) => hover(v), 30), [])
  const over = useCallback(
    (name: ItemName) => (e: any) => {
      e.stopPropagation()
      debouncedHover(name)
    },
    [debouncedHover],
  )
  const price = hovered ? prices[hovered] ?? prices.default : prices.default

  return (
    <>
      <group {...props}>
        <mesh geometry={nodes.vase1.geometry} material={materials.gray} material-envMap={env} />
        <mesh geometry={nodes.bottle.geometry} material={materials.gray} material-envMap={env} />
        <mesh geometry={nodes.walls_1.geometry} material={materials.floor} />
        <mesh geometry={nodes.walls_2.geometry} material={materials.walls} />
        <mesh geometry={nodes.plant_1.geometry} material={materials.potted_plant_01_leaves} />
        <mesh geometry={nodes.plant_2.geometry} material={materials.potted_plant_01_pot} />
        <mesh geometry={nodes.cuttingboard.geometry} material={materials.walls} />
        <mesh geometry={nodes.bowl.geometry} material={materials.walls} />
        <Select enabled={hovered === 'BRÖNDEN'} onPointerOver={over('BRÖNDEN')} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.carpet.geometry} material={materials.carpet} />
        </Select>
        <Select enabled={hovered === 'VOXLÖV'} onPointerOver={over('VOXLÖV')} onPointerOut={() => debouncedHover(null)}>
          <mesh
            geometry={nodes.table.geometry}
            material={materials.walls}
            material-envMap={env}
            material-envMapIntensity={0.5}
          />
        </Select>
        <Select enabled={hovered === 'FANBYN'} onPointerOver={over('FANBYN')} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.chairs_1.geometry} material={materials.walls} />
          <mesh
            geometry={nodes.chairs_2.geometry}
            material={materials.plastic}
            material-color="#1a1a1a"
            material-envMap={env}
          />
        </Select>
        <Select enabled={hovered === 'LIVSVERK'} onPointerOver={over('LIVSVERK')} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.vase.geometry} material={materials.gray} material-envMap={env} />
        </Select>
        <Select enabled={hovered === 'SKAFTET'} onPointerOver={over('SKAFTET')} onPointerOut={() => debouncedHover(null)}>
          <mesh geometry={nodes.lamp_socket.geometry} material={materials.gray} material-envMap={env} />
          <mesh geometry={nodes.lamp.geometry} material={materials.gray} />
          <mesh geometry={nodes.lamp_cord.geometry} material={materials.gray} material-envMap={env} />
        </Select>
        <mesh geometry={nodes.kitchen.geometry} material={materials.walls} />
        <mesh geometry={nodes.sink.geometry} material={materials.chrome} material-envMap={env} />
      </group>
      <Suspense fallback={null}>
        <Text position={[1, 1.25, 0]} color="black" fontSize={0.15} font={interFont} letterSpacing={-0.05}>
          {hovered ?? 'KNOXHULT'}
        </Text>
      </Suspense>

      <Price value={price} position={[-2, 0.3, -3.25]} />
    </>
  )
}

useGLTF.preload(kitchenModel)
